services:
  - type: static
    name: status-page-frontend
    env: static
    repo: https://github.com/yourusername/status-page.git # Replace with your GitHub repo URL
    rootDir: ./frontend
    buildCommand: "npm ci && npm run build:safe"
    publishDir: ./dist
    pullRequestPreviewsEnabled: false
    envVars:
      - key: VITE_CLERK_PUBLISHABLE_KEY
        sync: false # Set this manually in Render dashboard
      - key: VITE_API_URL
        value: https://status-page-backend.onrender.com # Replace with your backend URL
      - key: VITE_SOCKET_URL
        value: https://status-page-backend.onrender.com # Replace with your backend URL
      - key: VITE_ENVIRONMENT
        value: production
