services:
  - type: web
    name: status-page-backend
    env: python
    repo: https://github.com/ar0085/status-page
    rootDir: ./backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    plan: free # Change to 'starter' for production
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: DATABASE_URL
        fromDatabase:
          name: status-page-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CLERK_SECRET_KEY
        sync: false # You'll set this manually
      - key: FRONTEND_URL
        value: https://status-page-frontend.onrender.com
      - key: ENVIRONMENT
        value: production
      - key: CREATE_DEMO_DATA
        value: true # Set to true for one-time demo data creation
      - key: ALLOW_TEST_USERS
        value: true # Allow test users for demo purposes
    healthCheckPath: /health
